import { IApiAsnView } from '../edidb'
export class CApiAsnView implements IApiAsnView {
    public rownum:number = 0;
    public Asn_ID:number = 0;
    public Bol_No:string = '';
    public Pro_No:string = '';
    public ShipToPeps:boolean;
    public Ship_Weight:number = 0;
    public Ship_Date:string = '';
    public Del_Date:string = '';
    public Ship_Via_ID:string = '';
    public Asn_Complete:string = '';
    public Exp_Flag:string = '';
    public TP_PartID:string = '';
    public User1:string = '';
    public User2:string = '';
    public Trailer:string = '';
    public Collect:boolean;
    public AckID:string = '';
    public GCN:number = 0;
    public TCN:number = 0;
    public User3:string = '';
    public User4:string = '';
    public User5:string = '';
    public SealNo:string = '';
    public ExportDate:Date;
    public CreatedDate:Date;
    public PackImport:string = '';
    public VPIDFA:number = 0;
    public TP_Name:string = '';
    public NoteText:string = '';
    public constructor(init?:Partial<CApiAsnView>) { Object.assign(this, init); }
}
export const IApiAsnView_Bol_No_length = 30;
export const IApiAsnView_Pro_No_length = 30;
export const IApiAsnView_Ship_Date_length = 8;
export const IApiAsnView_Del_Date_length = 8;
export const IApiAsnView_Ship_Via_ID_length = 30;
export const IApiAsnView_Asn_Complete_length = 1;
export const IApiAsnView_Exp_Flag_length = 1;
export const IApiAsnView_TP_PartID_length = 30;
export const IApiAsnView_User1_length = 50;
export const IApiAsnView_User2_length = 50;
export const IApiAsnView_Trailer_length = 50;
export const IApiAsnView_AckID_length = 1;
export const IApiAsnView_User3_length = 50;
export const IApiAsnView_User4_length = 50;
export const IApiAsnView_User5_length = 50;
export const IApiAsnView_SealNo_length = 200;
export const IApiAsnView_PackImport_length = 1;
export const IApiAsnView_TP_Name_length = 30;
export const IApiAsnView_NoteText_length = 2000;

export const kApiAsnView_rownum="rownum";
export const kApiAsnView_Asn_ID="Asn_ID";
export const kApiAsnView_Bol_No="Bol_No";
export const kApiAsnView_Pro_No="Pro_No";
export const kApiAsnView_ShipToPeps="ShipToPeps";
export const kApiAsnView_Ship_Weight="Ship_Weight";
export const kApiAsnView_Ship_Date="Ship_Date";
export const kApiAsnView_Del_Date="Del_Date";
export const kApiAsnView_Ship_Via_ID="Ship_Via_ID";
export const kApiAsnView_Asn_Complete="Asn_Complete";
export const kApiAsnView_Exp_Flag="Exp_Flag";
export const kApiAsnView_TP_PartID="TP_PartID";
export const kApiAsnView_User1="User1";
export const kApiAsnView_User2="User2";
export const kApiAsnView_Trailer="Trailer";
export const kApiAsnView_Collect="Collect";
export const kApiAsnView_AckID="AckID";
export const kApiAsnView_GCN="GCN";
export const kApiAsnView_TCN="TCN";
export const kApiAsnView_User3="User3";
export const kApiAsnView_User4="User4";
export const kApiAsnView_User5="User5";
export const kApiAsnView_SealNo="SealNo";
export const kApiAsnView_ExportDate="ExportDate";
export const kApiAsnView_CreatedDate="CreatedDate";
export const kApiAsnView_PackImport="PackImport";
export const kApiAsnView_VPIDFA="VPIDFA";
export const kApiAsnView_TP_Name="TP_Name";
export const kApiAsnView_NoteText="NoteText";
