import { IGetTradeChunkResult } from '../edidb'
export class CGetTradeChunkResult implements IGetTradeChunkResult {
    public LOCATION_IN_RECORD_SET:number = 0;
    public PAGE_NUMBER:number = 0;
    public TP_PartID:string = '';
    public TP_PartQ:string = '';
    public TP_ID:string = '';
    public TP_Name:string = '';
    public TP_GroupID:string = '';
    public TP_Asn:string = '';
    public TP_ItemCode:string = '';
    public TP_UseN1BY:string = '';
    public TP_UseDept:string = '';
    public TP_UseN1ST:string = '';
    public TP_STQUAL:string = '';
    public TP_In850:string = '';
    public TP_In810:string = '';
    public TP_Out850:string = '';
    public TP_Out810:string = '';
    public TP_864ID:string = '';
    public TP_ShipDateQual:string = '';
    public TP_CancelDateQual:string = '';
    public Std_ID:string = '';
    public Term_Days:string = '';
    public Disc_Perc:string = '';
    public Disc_Days:string = '';
    public TP_VendID:string = '';
    public TP_MapIn_850:string = '';
    public TP_UCC128:string = '';
    public TP_BarcodeType:string = '';
    public TP_User1:string = '';
    public TP_User2:string = '';
    public TP_User3:string = '';
    public TP_User4:string = '';
    public TP_User5:string = '';
    public TP_User6:string = '';
    public TP_User7:string = '';
    public TP_User8:string = '';
    public TP_User9:string = '';
    public TP_ItemCode2:string = '';
    public TP_STformat:number = 0;
    public TP_SendQ:string = '';
    public TP_SendID:string = '';
    public TP_SendGID:string = '';
    public TP_EleSep:number = 0;
    public TP_SubEleSep:number = 0;
    public TP_SegTerm:number = 0;
    public CreateFA:boolean;
    public Create856:boolean;
    public Van:string = '';
    public UseAltAdr:boolean;
    public ISA14Y:boolean;
    public Exp_Date:Date;
    public CipherKey:string = '';
    public TP_Out753:boolean;
    public CalcLineTax:boolean;
    public UseCurrency:boolean;
    public PrcMethod:number = 0;
    public SerLotFlag:boolean;
    public TP_ShipDateQual1:string = '';
    public TP_ShipDateQual2:string = '';
    public TP_CancelDateQual1:string = '';
    public TP_CancelDateQual2:string = '';
    public PostSAC:boolean;
    public Pseudo_ID:string = '';
    public Pseudo_Segname:string = '';
    public Pseudo_Qual_Elem_No:number = 0;
    public Pseudo_Qual_Elem_Value:string = '';
    public Pseudo_Vendor_Elem_No:number = 0;
    public Pseudo_Vendor_Elem_Value:string = '';
    public Pseudo_TPPartID:string = '';
    public ForceSerLot:boolean;
    public PO_Exclude_Types:string = '';
    public PKG_ID:string = '';
    public KitTypeID:number = 0;
    public PackSizeLookupSeq:string = '';
    public TP_RepSep:number = 0;
    public TP_QuoteOrder:boolean;
    public PSPOMethod:number = 0;
    public TP_STQUAL2:string = '';
    public PostCommentsToAcct:boolean;
    public CreditMemoAsInvoice:boolean;
    public AddlAdrQual1:string = '';
    public AddlAdrQual2:string = '';
    public UsePackingClass:boolean;
    public TransitDays:number = 0;
    public FrozenDays:number = 0;
    public ShipDlvPattern:string = '';
    public TP_GS1Prefix:string = '';
    public TP_UseGS1Prefix:boolean;
    public Loc_Override:string = '';
    public TP_Status:string = '';
    public constructor(init?:Partial<CGetTradeChunkResult>) { Object.assign(this, init); }
}
export const kGetTradeChunkResult_LOCATION_IN_RECORD_SET="LOCATION_IN_RECORD_SET";
export const kGetTradeChunkResult_PAGE_NUMBER="PAGE_NUMBER";
export const kGetTradeChunkResult_TP_PartID="TP_PartID";
export const kGetTradeChunkResult_TP_PartQ="TP_PartQ";
export const kGetTradeChunkResult_TP_ID="TP_ID";
export const kGetTradeChunkResult_TP_Name="TP_Name";
export const kGetTradeChunkResult_TP_GroupID="TP_GroupID";
export const kGetTradeChunkResult_TP_Asn="TP_Asn";
export const kGetTradeChunkResult_TP_ItemCode="TP_ItemCode";
export const kGetTradeChunkResult_TP_UseN1BY="TP_UseN1BY";
export const kGetTradeChunkResult_TP_UseDept="TP_UseDept";
export const kGetTradeChunkResult_TP_UseN1ST="TP_UseN1ST";
export const kGetTradeChunkResult_TP_STQUAL="TP_STQUAL";
export const kGetTradeChunkResult_TP_In850="TP_In850";
export const kGetTradeChunkResult_TP_In810="TP_In810";
export const kGetTradeChunkResult_TP_Out850="TP_Out850";
export const kGetTradeChunkResult_TP_Out810="TP_Out810";
export const kGetTradeChunkResult_TP_864ID="TP_864ID";
export const kGetTradeChunkResult_TP_ShipDateQual="TP_ShipDateQual";
export const kGetTradeChunkResult_TP_CancelDateQual="TP_CancelDateQual";
export const kGetTradeChunkResult_Std_ID="Std_ID";
export const kGetTradeChunkResult_Term_Days="Term_Days";
export const kGetTradeChunkResult_Disc_Perc="Disc_Perc";
export const kGetTradeChunkResult_Disc_Days="Disc_Days";
export const kGetTradeChunkResult_TP_VendID="TP_VendID";
export const kGetTradeChunkResult_TP_MapIn_850="TP_MapIn_850";
export const kGetTradeChunkResult_TP_UCC128="TP_UCC128";
export const kGetTradeChunkResult_TP_BarcodeType="TP_BarcodeType";
export const kGetTradeChunkResult_TP_User1="TP_User1";
export const kGetTradeChunkResult_TP_User2="TP_User2";
export const kGetTradeChunkResult_TP_User3="TP_User3";
export const kGetTradeChunkResult_TP_User4="TP_User4";
export const kGetTradeChunkResult_TP_User5="TP_User5";
export const kGetTradeChunkResult_TP_User6="TP_User6";
export const kGetTradeChunkResult_TP_User7="TP_User7";
export const kGetTradeChunkResult_TP_User8="TP_User8";
export const kGetTradeChunkResult_TP_User9="TP_User9";
export const kGetTradeChunkResult_TP_ItemCode2="TP_ItemCode2";
export const kGetTradeChunkResult_TP_STformat="TP_STformat";
export const kGetTradeChunkResult_TP_SendQ="TP_SendQ";
export const kGetTradeChunkResult_TP_SendID="TP_SendID";
export const kGetTradeChunkResult_TP_SendGID="TP_SendGID";
export const kGetTradeChunkResult_TP_EleSep="TP_EleSep";
export const kGetTradeChunkResult_TP_SubEleSep="TP_SubEleSep";
export const kGetTradeChunkResult_TP_SegTerm="TP_SegTerm";
export const kGetTradeChunkResult_CreateFA="CreateFA";
export const kGetTradeChunkResult_Create856="Create856";
export const kGetTradeChunkResult_Van="Van";
export const kGetTradeChunkResult_UseAltAdr="UseAltAdr";
export const kGetTradeChunkResult_ISA14Y="ISA14Y";
export const kGetTradeChunkResult_Exp_Date="Exp_Date";
export const kGetTradeChunkResult_CipherKey="CipherKey";
export const kGetTradeChunkResult_TP_Out753="TP_Out753";
export const kGetTradeChunkResult_CalcLineTax="CalcLineTax";
export const kGetTradeChunkResult_UseCurrency="UseCurrency";
export const kGetTradeChunkResult_PrcMethod="PrcMethod";
export const kGetTradeChunkResult_SerLotFlag="SerLotFlag";
export const kGetTradeChunkResult_TP_ShipDateQual1="TP_ShipDateQual1";
export const kGetTradeChunkResult_TP_ShipDateQual2="TP_ShipDateQual2";
export const kGetTradeChunkResult_TP_CancelDateQual1="TP_CancelDateQual1";
export const kGetTradeChunkResult_TP_CancelDateQual2="TP_CancelDateQual2";
export const kGetTradeChunkResult_PostSAC="PostSAC";
export const kGetTradeChunkResult_Pseudo_ID="Pseudo_ID";
export const kGetTradeChunkResult_Pseudo_Segname="Pseudo_Segname";
export const kGetTradeChunkResult_Pseudo_Qual_Elem_No="Pseudo_Qual_Elem_No";
export const kGetTradeChunkResult_Pseudo_Qual_Elem_Value="Pseudo_Qual_Elem_Value";
export const kGetTradeChunkResult_Pseudo_Vendor_Elem_No="Pseudo_Vendor_Elem_No";
export const kGetTradeChunkResult_Pseudo_Vendor_Elem_Value="Pseudo_Vendor_Elem_Value";
export const kGetTradeChunkResult_Pseudo_TPPartID="Pseudo_TPPartID";
export const kGetTradeChunkResult_ForceSerLot="ForceSerLot";
export const kGetTradeChunkResult_PO_Exclude_Types="PO_Exclude_Types";
export const kGetTradeChunkResult_PKG_ID="PKG_ID";
export const kGetTradeChunkResult_KitTypeID="KitTypeID";
export const kGetTradeChunkResult_PackSizeLookupSeq="PackSizeLookupSeq";
export const kGetTradeChunkResult_TP_RepSep="TP_RepSep";
export const kGetTradeChunkResult_TP_QuoteOrder="TP_QuoteOrder";
export const kGetTradeChunkResult_PSPOMethod="PSPOMethod";
export const kGetTradeChunkResult_TP_STQUAL2="TP_STQUAL2";
export const kGetTradeChunkResult_PostCommentsToAcct="PostCommentsToAcct";
export const kGetTradeChunkResult_CreditMemoAsInvoice="CreditMemoAsInvoice";
export const kGetTradeChunkResult_AddlAdrQual1="AddlAdrQual1";
export const kGetTradeChunkResult_AddlAdrQual2="AddlAdrQual2";
export const kGetTradeChunkResult_UsePackingClass="UsePackingClass";
export const kGetTradeChunkResult_TransitDays="TransitDays";
export const kGetTradeChunkResult_FrozenDays="FrozenDays";
export const kGetTradeChunkResult_ShipDlvPattern="ShipDlvPattern";
export const kGetTradeChunkResult_TP_GS1Prefix="TP_GS1Prefix";
export const kGetTradeChunkResult_TP_UseGS1Prefix="TP_UseGS1Prefix";
export const kGetTradeChunkResult_Loc_Override="Loc_Override";
export const kGetTradeChunkResult_TP_Status="TP_Status";
