import { IItem } from '../edidb'
export class CItem implements IItem {
    public Int_Item_No:string = '';
    public Item_Desc:string = '';
    public UPC:string = '';
    public Def_Pack_Qty:number = 0;
    public Item_Wt:number = 0;
    public Item_Um:string = '';
    public Item_UOM:string = '';
    public EDI_UOM:string = '';
    public RetailPrice:number = 0;
    public SellingPrice:number = 0;
    public SAC_Flag:boolean;
    public SAC_Qual:string = '';
    public Cube_Length:number = 0;
    public Cube_Width:number = 0;
    public Cube_Height:number = 0;
    public Cube_Qty:number = 0;
    public Cube_UOM:string = '';
    public User1:string = '';
    public User2:string = '';
    public User3:string = '';
    public User4:string = '';
    public User5:string = '';
    public Item_rfid:boolean;
    public locid:string = '';
    public PackingClass:string = '';
    public Item_Alt_No:string = '';
    public Item_Config:string = '';
    public Item_Size:string = '';
    public Item_Color:string = '';
    public Frt_Code:string = '';
    public GTIN:string = '';
    public EAN:string = '';
    public constructor(init?:Partial<CItem>) { Object.assign(this, init); }
}
export const IItem_Int_Item_No_length = 500;
export const IItem_Item_Desc_length = 80;
export const IItem_UPC_length = 20;
export const IItem_Item_Um_length = 3;
export const IItem_Item_UOM_length = 10;
export const IItem_EDI_UOM_length = 3;
export const IItem_SAC_Qual_length = 4;
export const IItem_Cube_UOM_length = 2;
export const IItem_User1_length = 50;
export const IItem_User2_length = 50;
export const IItem_User3_length = 50;
export const IItem_User4_length = 50;
export const IItem_User5_length = 50;
export const IItem_locid_length = 20;
export const IItem_PackingClass_length = 30;
export const IItem_Item_Alt_No_length = 30;
export const IItem_Item_Config_length = 30;
export const IItem_Item_Size_length = 30;
export const IItem_Item_Color_length = 30;
export const IItem_Frt_Code_length = 50;
export const IItem_GTIN_length = 20;
export const IItem_EAN_length = 20;
