export const LOAD_DATA ="LOAD_DATA";
export const LOAD_ERROR ="LOAD_ERROR";

export const ADD_TEST_NOTIFICATION = "ADD_TEST_NOTIFICATION";
export const LOAD_NEWS_FEED_SUCCESS = "LOAD_NEWS_FEED_SUCCESS";
export const LOAD_ALERT_GROUP_SUCCESS ="LOAD_ALERT_GROUP_SUCCESS";
export const LOAD_ALERT_GROUP_DETAILS_SUCCESS ="LOAD_ALERT_GROUP_DETAILS_SUCCESS";
export const LOAD_TOP_ERROR_LOGS = "LOAD_TOP_ERROR_LOGS";
export const LOAD_DOC_RECEIVED_COUNT = "LOAD_DOC_RECEIVED_COUNT";