export const LOAD_DATA ="LOAD_DATA";
export const LOAD_ERROR ="LOAD_ERROR";

export const ADD_TEST_NOTIFICATION = "ADD_TEST_NOTIFICATION";
export const LOAD_NEWS_FEED_SUCCESS = "LOAD_NEWS_FEED_SUCCESS";